In [2]:
import numpy as np
import torch
from matplotlib import pyplot as plt

In [3]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [4]:
torch.tensor([[1,2],[3,4]],device="cuda:0")

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [5]:
torch.tensor([[1,2],[3,4]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [6]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
t = torch.zeros(100,10).to("cuda:0")

In [8]:
t.size()

torch.Size([100, 10])

In [10]:
t = torch.tensor([[1,2],[3,4.]])
x = t.numpy()

In [11]:
t = torch.tensor([[1,2],[3,4.]], device="cuda:0")
x = t.cpu().numpy()

In [12]:
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Tensor

In [13]:
x = torch.randn(100,3)

In [15]:
a = torch.tensor([1,2,3.], requires_grad=True)

y = torch.mv(x,a)
o = y.sum()

o.backward()
a.grad != x.sum(0)

tensor([False,  True,  True])